// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0RrSE5sOG5oV3FpSElmRGFTVTZtNVByYXFTcHN2cEJ2aUlHbXM4aitHMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTzFBb0d4NzZYdlRHTUZuZTdaaC9qSkVsbVdncXJVM3BPcDM4ZG1oN3BYWT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJTUGpDV21UT0RpWHVHQ1UrSnduNG16NHp1d1p6YjlvYzFJQVZEbmRJNWtnPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDcTMzQWVpTkJ5ZVNIZFVyRGJXV3hyZFRFdVB3aWdlSU12elZJKzZpVkZjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9PTmxEcTZKN21jcVQvTVU0ZnRVUVZMNVNyMUZJYlA5cS92TVNUcEJ4WHc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFpaGtsZStRcThreDU3MjB2aWxwOFkxSTdlZEhDKzQ1L0dqUnNnYSszU1k9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR0R4OWIwS2R3bFJJY0M1QXRqYUpBeW9UUEMxWjVRdEZ5dzMvYktwZzdsZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieGZxcE9DbEpkK0gyNjJnSHZackNQUlE2MTU2YjRUSzYyc2xheW1pYmJqZz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkpISTVwSDdEUms1eW1qY3BFTWVCWEdYbG92UUlON3BFN1VhL1NSb1VOczNwajZ1ZGJ0aDhuWkRZSWxnL2MyQXUrd251eDNMd21FSG10QjhJVFlvY0RRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTM4LCJhZHZTZWNyZXRLZXkiOiJWTkRqNEFWMW1UVlJTZEgzNS9Td25OK1JFTDhmVFBtNVpqRUFqbkI2L0xnPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJZaUNDTjA3VVJVdTdFby15S2IyNkhRIiwicGhvbmVJZCI6ImQ4MTNiN2IxLWM4NjktNGI1Mi04MTdlLWUxZTAyMjBlNTQ4ZCIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIyRzJyaTVpVXhGeldvY01SVkh2a29BLzUzYWs9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZTdwb1VUYXZkOWRIS09LTlE3WDZUdVlSdk1nPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjkxNFA0SkxDIiwibWUiOnsiaWQiOiI5MjMyMjUyOTQ2MDU6OUBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSUtkcDU0R0VMNldwcm9HR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiL2VWanRkTm5hRFV4YnFTQzFYY0g2Q05vd0Vya2RmWndBaXJPRzVEQ1B4ST0iLCJhY2NvdW50U2lnbmF0dXJlIjoicmRoUG5wcGsrNVBCNUNzREF4V1hxYU1WTTZnbXpPUWs0U1Q2NTNtdTMzMHlCTVdGZ1F3bUpMNzlqYmtBMFZHck5vME9ROUZiOWhPd1N5V0QycUhiQlE9PSIsImRldmljZVNpZ25hdHVyZSI6Im5PS1FDWWNiaGdNMzZUd1lsQW9aS2tvSkFtVi9tcERtZVFla3VaZjNCcitCWVczQnU0UEVGYXZjMlI4cGNza1BHUTBSVHYrSmFLOC83V2laaEM3bkJ3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzMjI1Mjk0NjA1OjlAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZjNsWTdYVFoyZzFNVzZrZ3RWM0IrZ2phTUJLNUhYMmNBSXF6aHVRd2o4UyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczMjg3MzA0MCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFEMDUifQ==",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "©yessertech",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "255621995482",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
